package pageobject;

import org.openqa.selenium.WebDriver;
import pagefactory.Create_MarginorderFactory;

import java.util.concurrent.TimeUnit;

/**
 * @Authot: Jomi Gan
 * @Description:
 * @Date: Create in 15:52 2020/1/13
 **/
public class CreateMarginAuctionObject {
    WebDriver driver;

    public CreateMarginAuctionObject(WebDriver driver){
        this.driver = driver;
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    }

//第一种场次组合
    /*
    价格类型：升贴水
    成交计价模式：申报价成交
    交收方式：协商交收
    是否指定指定单位：否
    黑白名单：不启用
    合同类型：日合同
     */
    public void CreateAuction1(String marginordername,String bidweight,String minweight,String maxweight,String linkman,String contactphone,String settlecycle,String basepriceshow,String bidperprice,String bidperpeight
    ) throws InterruptedException {
        Create_MarginorderFactory createOrderFactory = new Create_MarginorderFactory(driver);
        //点击交易管理顶部菜单栏
        createOrderFactory.setTradeManagement_menu();
        //点击我是卖家按钮
        createOrderFactory.setSellerPage_menu();
        //点击竞拍发起主菜单
        createOrderFactory.setAuctionmenu();
        //选择发起竞拍菜单
        createOrderFactory.setCreatenewauctionordermenu();
        Thread.sleep(1000);
        //点击产品名称按钮
        createOrderFactory.setProductName_botton();
        Thread.sleep(2000);

        //选择天然气父品种
        createOrderFactory.setListingmenufirstfloorpng();
        Thread.sleep(2000);
        //选择对应的产品名称：管道天然气（门站）
        createOrderFactory.setAgreementtranscactionpng1();
        Thread.sleep(1000);
        //点击确定按钮
        createOrderFactory.setDeterMine_botton();
        Thread.sleep(1000);

        //点击下一步按钮
        createOrderFactory.setNextStep_Botton2();
        Thread.sleep(1000);
        //设置场次名称
        createOrderFactory.setOrderName(marginordername);
        //设置公告日期
        createOrderFactory.setNoticeDate();
        //设置竞拍日期
        createOrderFactory.setBidDate();
        //设置竞拍开始时间
        createOrderFactory.setBeginTime();
        //设置竞拍结束时间
        createOrderFactory.setEndTime();
        //设置竞标挂牌量
        createOrderFactory.setBiddingW(bidweight);
        //设置最小交易量
        createOrderFactory.setMinWeight(minweight);
        //设置联系人
        createOrderFactory.setLinkMan(linkman);
        //设置联系电话
        createOrderFactory.setContactPhone(contactphone);
        //设置交收方式为：协商交收
        createOrderFactory.setSettType0();
        //设置付款条件为先货后款
        createOrderFactory.setPaytype0();
        //设置最大交易量
        createOrderFactory.setMaxWeight(maxweight);
        //设置交收周期
        createOrderFactory.setSettleCycle(settlecycle);
        //设置是否指定执行单位为：否
        createOrderFactory.setIsExecu0();
        //合同类型设置为：日合同
        createOrderFactory.setContractType_day();
        //设置交收起始日
        createOrderFactory.setSettlementDate();
        //设置销售对象类型为:天然气生产
        Thread.sleep(1000);
        createOrderFactory.setCompanyTypeView();
        //设置商品运输为：卖方包运
        createOrderFactory.setShipType_info();
        //设置交收地点为：重庆
        createOrderFactory.setProvinceView1();
        //设置门站价浮动比例
        createOrderFactory.setBasePriceShow(basepriceshow);
        //设置最小变动价位
        createOrderFactory.setBidPerPrice(bidperprice);
        //设置最小交易单位
        createOrderFactory.setBidPerWeight(bidperpeight);
        Thread.sleep(1000);
        //点击保存并提交按钮
        createOrderFactory.setSubmmit();
        //确认提交按钮
        createOrderFactory.setSure();
        Thread.sleep(2000);
        //关闭浏览器
        driver.close();
    }


//第二种场次组合
    /*
    价格类型：升贴水
    成交计价模式：申报价成交
    交收方式：线下交收
    是否指定指定单位：否
    黑白名单：不启用
    合同类型：周合同
     */
    public void CreateAuction2(String marginordername,String bidweight,String minweight,String maxweight,String linkman,String contactphone,String settlecycleweek,String basepriceshow,String bidperprice,String bidperpeight
    ) throws InterruptedException {
        Create_MarginorderFactory createOrderFactory = new Create_MarginorderFactory(driver);
        //点击交易管理顶部菜单栏
        createOrderFactory.setTradeManagement_menu();
        //点击我是卖家按钮
        createOrderFactory.setSellerPage_menu();
        //点击竞拍发起主菜单
        createOrderFactory.setAuctionmenu();
        //选择发起竞拍菜单
        createOrderFactory.setCreatenewauctionordermenu();
        //点击产品名称按钮
        createOrderFactory.setProductName_botton();
        //选择天然气父品种
        createOrderFactory.setListingmenufirstfloorpng();
        Thread.sleep(2000);
        //选择对应的产品名称：管道天然气（门站）
        createOrderFactory.setAgreementtranscactionpng1();
        Thread.sleep(1000);
        //点击确定按钮
        createOrderFactory.setDeterMine_botton();
        Thread.sleep(1000);
        //点击下一步按钮
        createOrderFactory.setNextStep_Botton2();
        Thread.sleep(1000);
        //设置场次名称
        createOrderFactory.setOrderName(marginordername);
        //设置公告日期
        createOrderFactory.setNoticeDate();
        //设置竞拍日期
        createOrderFactory.setBidDate();
        //设置竞拍开始时间
        createOrderFactory.setBeginTime();
        //设置竞拍结束时间
        createOrderFactory.setEndTime();
        //设置竞标挂牌量
        createOrderFactory.setBiddingW(bidweight);
        //设置最小交易量
        createOrderFactory.setMinWeight(minweight);
        //设置联系人
        createOrderFactory.setLinkMan(linkman);
        //设置联系电话
        createOrderFactory.setContactPhone(contactphone);
        //设置交收方式为：线下交收
        createOrderFactory.setSettType1();
        //设置最大交易量
        createOrderFactory.setMaxWeight(maxweight);
        //设置交收周期
        createOrderFactory.setSettleCycle(settlecycleweek);
        Thread.sleep(1000);
        //合同类型设置为：周合同
        createOrderFactory.setContractType_week();
        //设置交收起始日
        createOrderFactory.setSettlementDate();
        //设置销售对象类型为:天然气生产
        Thread.sleep(2000);
        createOrderFactory.setCompanyTypeView();
        //设置商品运输为：卖方包运
        createOrderFactory.setShipType_info();
        //设置交收地点为：重庆
        createOrderFactory.setProvinceView1();
        //设置门站价浮动比例
        createOrderFactory.setBasePriceShow(basepriceshow);
        //设置最小变动价位
        createOrderFactory.setBidPerPrice(bidperprice);
        //设置最小交易单位
        createOrderFactory.setBidPerWeight(bidperpeight);
        Thread.sleep(2000);

        //点击保存并提交按钮
        createOrderFactory.setSubmmit();
        Thread.sleep(2000);

        //确认提交按钮
        createOrderFactory.setSure();
        Thread.sleep(2000);
        //关闭浏览器
        driver.close();
    }


//第三种场次组合
    /*
    价格类型：升贴水
    成交计价模式：申报价成交
    交收方式：协商交收
    是否指定指定单位：是（系统提前设定）
    黑白名单：不启用
    合同类型：日合同
     */
    public void CreateAuction3(String marginordername,String bidweight,String minweight,String maxweight,String linkman,String contactphone,String settlecycle,String basepriceshow,String bidperprice,String bidperpeight
    ) throws InterruptedException {
        Create_MarginorderFactory createOrderFactory = new Create_MarginorderFactory(driver);
        //点击交易管理顶部菜单栏
        createOrderFactory.setTradeManagement_menu();
        //点击我是卖家按钮
        createOrderFactory.setSellerPage_menu();
        //点击竞拍发起主菜单
        createOrderFactory.setAuctionmenu();
        //选择发起竞拍菜单
        createOrderFactory.setCreatenewauctionordermenu();
        //点击产品名称按钮
        createOrderFactory.setProductName_botton();
        Thread.sleep(1000);
        //选择天然气父品种
        createOrderFactory.setListingmenufirstfloorpng();
        Thread.sleep(2000);
        //选择对应的产品名称：管道天然气（门站）
        createOrderFactory.setAgreementtranscactionpng1();
        Thread.sleep(1000);
        //点击确定按钮
        createOrderFactory.setDeterMine_botton();
        Thread.sleep(1000);
        //点击下一步按钮
        createOrderFactory.setNextStep_Botton2();
        Thread.sleep(1000);
        //设置场次名称
        createOrderFactory.setOrderName(marginordername);
        //设置公告日期
        createOrderFactory.setNoticeDate();
        //设置竞拍日期
        createOrderFactory.setBidDate();
        //设置竞拍开始时间
        createOrderFactory.setBeginTime();
        //设置竞拍结束时间
        createOrderFactory.setEndTime();
        //设置竞标挂牌量
        createOrderFactory.setBiddingW(bidweight);
        //设置最小交易量
        createOrderFactory.setMinWeight(minweight);
        //设置联系人
        createOrderFactory.setLinkMan(linkman);
        //设置联系电话
        createOrderFactory.setContactPhone(contactphone);
        //设置交收方式为：协商交收
        createOrderFactory.setSettType0();
        //设置最大交易量
        createOrderFactory.setMaxWeight(maxweight);
        //设置交收周期
        createOrderFactory.setSettleCycle(settlecycle);
        //设置是否指定执行单位为：否
        //设置是否指定执行单位为：系统提前设定
        createOrderFactory.setIsExecu1();
        createOrderFactory.setSelectExecusbotton();
        createOrderFactory.setChooseexecus();
        createOrderFactory.setDobotton();
        //合同类型设置为：日合同
        createOrderFactory.setContractType_month();
        //设置交收起始日
        createOrderFactory.setSettlementDate();
        //设置销售对象类型为:天然气生产
        Thread.sleep(2);
        createOrderFactory.setCompanyTypeView();
        //设置商品运输为：卖方包运
        createOrderFactory.setShipType_info();
        //设置交收地点为：重庆
        createOrderFactory.setProvinceView1();
        //设置门站价浮动比例
        createOrderFactory.setBasePriceShow(basepriceshow);
        //设置最小变动价位
        createOrderFactory.setBidPerPrice(bidperprice);
        //设置最小交易单位
        createOrderFactory.setBidPerWeight(bidperpeight);
        //点击保存并提交按钮
        createOrderFactory.setSubmmit();
        //确认提交按钮
        createOrderFactory.setSure();
        Thread.sleep(3000);
        //关闭浏览器
        driver.close();
    }


    //第四种场次组合
    /*
        管道天然气（门站）
        价格类型：商品价
        成交计价模式：单一底价成交
        交收方式：协商交收
        交收周期：30
        系统提前指定执行单位
        摘单方式：保证金摘单
        合同类型：月合同
        商品运输：卖方包运
     */
    public void CreateAuction4(String marginordername,String bidweight,String minweight,String maxweight,String linkman,String contactphone,String settlecycle,String basepriceshow,String bidperprice,String bidperpeight
    ) throws InterruptedException {
        Create_MarginorderFactory createOrderFactory = new Create_MarginorderFactory(driver);
        //点击交易管理顶部菜单栏
        createOrderFactory.setTradeManagement_menu();
        //点击我是卖家按钮
        createOrderFactory.setSellerPage_menu();
        //点击竞拍发起主菜单
        createOrderFactory.setAuctionmenu();
        //选择发起竞拍菜单
        createOrderFactory.setCreatenewauctionordermenu();
        Thread.sleep(1000);
        //点击产品名称按钮
        createOrderFactory.setProductName_botton();
        Thread.sleep(1000);
        //选择天然气父品种
        createOrderFactory.setListingmenufirstfloorpng();
        Thread.sleep(2000);
        //选择对应的产品名称：管道天然气（门站）
        createOrderFactory.setAgreementtranscactionpng1();
        Thread.sleep(1000);
        //点击确定按钮
        createOrderFactory.setDeterMine_botton();
        Thread.sleep(1000);
        //点击下一步按钮
        createOrderFactory.setNextStep_Botton2();
        Thread.sleep(1000);
        //设置场次名称
        createOrderFactory.setOrderName(marginordername);
        //设置公告日期
        createOrderFactory.setNoticeDate();
        //设置竞拍日期
        createOrderFactory.setBidDate();
        //设置竞拍开始时间
        createOrderFactory.setBeginTime();
        //设置竞拍结束时间
        createOrderFactory.setEndTime();
        //设置竞标挂牌量
        createOrderFactory.setBiddingW(bidweight);
        //设置最小交易量
        createOrderFactory.setMinWeight(minweight);
        //价格类型为升贴水
        //设置联系人
        createOrderFactory.setLinkMan(linkman);
        //设置联系电话
        createOrderFactory.setContactPhone(contactphone);
        //设置交收方式为：协商交收
        createOrderFactory.setSettType0();
        //设置最大交易量
        createOrderFactory.setMaxWeight(maxweight);
        //设置交收周期：月
        createOrderFactory.setSettleCycle(settlecycle);
        //设置是否指定执行单位为：系统临时指定
        createOrderFactory.setIsExecu1();
        //合同类型设置为：月合同
        createOrderFactory.setContractType_month();
        //设置交收起始日
        createOrderFactory.setSettlementDate();
        //设置销售对象类型为:天然气生产
        Thread.sleep(2);
        createOrderFactory.setCompanyTypeView();
        //设置商品运输为：卖方包运
        createOrderFactory.setShipType_info();
        //设置交收地点为：重庆
        createOrderFactory.setProvinceView1();
        //设置门站价浮动比例
        createOrderFactory.setBasePriceShow(basepriceshow);
        //设置最小变动价位
        createOrderFactory.setBidPerPrice(bidperprice);
        //设置最小交易单位
        createOrderFactory.setBidPerWeight(bidperpeight);
        //点击保存并提交按钮
        createOrderFactory.setSubmmit();
        //确认提交按钮
        createOrderFactory.setSure();
        Thread.sleep(3000);
        //关闭浏览器
        driver.close();
    }


    //第五种场次组合
    /*
        液化天然气（LNG）
        价格类型：商品价
        成交计价模式：申报价成交
        交收方式：协商交收
        交收周期：30
        不指定执行单位
        摘单方式：保证金摘单
        合同类型：月合同
        商品运输：卖方包运
     */
    public void CreateAuction5(String marginordername,String bidweight,String minweight,String maxweight,String linkman,String contactphone,String settlecycle,String baseprice,String bidperprice,String bidperpeight,String gasRatenum
    ) throws InterruptedException {
        Create_MarginorderFactory createOrderFactory = new Create_MarginorderFactory(driver);
        //点击交易管理顶部菜单栏
        createOrderFactory.setTradeManagement_menu();
        //点击我是卖家按钮
        createOrderFactory.setSellerPage_menu();
        //点击竞拍发起主菜单
        createOrderFactory.setAuctionmenu();
        //选择发起竞拍菜单
        createOrderFactory.setCreatenewauctionordermenu();
        //点击产品名称按钮
        createOrderFactory.setProductName_botton();
        Thread.sleep(1000);
        //选择天然气父品种
        createOrderFactory.setType();
        Thread.sleep(1000);
        //选择对应的产品名称：液化天然气（LNG）
        createOrderFactory.setAgreementtranscactionlng1();
        Thread.sleep(1000);
        //点击确定按钮
        createOrderFactory.setDeterMine_botton();
        Thread.sleep(1000);
        //点击下一步按钮
        createOrderFactory.setNextStep_Botton2();
        Thread.sleep(1000);
        //设置场次名称
        createOrderFactory.setOrderName(marginordername);
        //设置公告日期
        createOrderFactory.setNoticeDate();
        //设置竞拍日期
        createOrderFactory.setBidDate();
        //设置竞拍开始时间
        createOrderFactory.setBeginTime();
        //设置竞拍结束时间
        createOrderFactory.setEndTime();
        //设置竞标挂牌量
        createOrderFactory.setBiddingW(bidweight);
        //设置最小交易量
        createOrderFactory.setMinWeight(minweight);
        //价格类型为商品价
        //设置联系人
        createOrderFactory.setLinkMan(linkman);
        //设置联系电话
        createOrderFactory.setContactPhone(contactphone);
        //设置交收方式为：协商交收
        createOrderFactory.setSettType0();
        //设置最大交易量
        createOrderFactory.setMaxWeight(maxweight);
        //设置交收周期：月
        createOrderFactory.setSettleCycle(settlecycle);
        //设置不指定执行单位
        //合同类型设置为：月合同
        createOrderFactory.setContractType_month();
        //设置交收起始日
        createOrderFactory.setSettlementDate();
        //设置销售对象类型为:天然气生产
        Thread.sleep(1000);
        createOrderFactory.setCompanyTypeView();
        //设置商品运输为：卖方包运
        createOrderFactory.setShipType_info();
        Thread.sleep(2000);
        //设置交收地点为：重庆
        createOrderFactory.setProvinceView2();
        //设置门站价浮动比例
        createOrderFactory.setBasePriceShow(baseprice);
        //设置最小变动价位
        createOrderFactory.setBidPerPrice(bidperprice);
        //设置最小交易单位
        createOrderFactory.setBidPerWeight(bidperpeight);
        //设置气化率
        createOrderFactory.setGasRate(gasRatenum);
        Thread.sleep(3000);
        //点击保存并提交按钮
        createOrderFactory.setSubmmit();
        //确认提交按钮
        createOrderFactory.setSure();
        Thread.sleep(3000);
        //关闭浏览器
        driver.close();
    }


    //第六种场次组合
    /*
        液化天然气（LNG）
        价格类型：商品价
        成交计价模式：申报价成交
        交收方式：协商交收
        交收周期：30
        不指定执行单位
        摘单方式：保证金摘单
        合同类型：月合同
        商品运输：卖方包运
     */
    public void CreateAuction6(String marginordername,String bidweight,String minweight,String maxweight,String linkman,String contactphone,String settlecycle,String baseprice,String bidperprice,String bidperpeight,String gasRatenum
    ) throws InterruptedException {
        Create_MarginorderFactory createOrderFactory = new Create_MarginorderFactory(driver);
        //点击交易管理顶部菜单栏
        createOrderFactory.setTradeManagement_menu();
        //点击我是卖家按钮
        createOrderFactory.setSellerPage_menu();
        //点击竞拍发起主菜单
        createOrderFactory.setAuctionmenu();
        //选择发起竞拍菜单
        createOrderFactory.setCreatenewauctionordermenu();
        //点击产品名称按钮
        createOrderFactory.setProductName_botton();
        Thread.sleep(1000);
        //选择天然气父品种
        createOrderFactory.setType();
        Thread.sleep(1000);
        //选择对应的产品名称：液化天然气（LNG）
        createOrderFactory.setAgreementtranscactionlng1();
        Thread.sleep(1000);
        //点击确定按钮
        createOrderFactory.setDeterMine_botton();
        Thread.sleep(1500);
        //点击下一步按钮
        createOrderFactory.setNextStep_Botton2();
        //设置场次名称
        createOrderFactory.setOrderName(marginordername);
        //设置公告日期
        createOrderFactory.setNoticeDate();
        //设置竞拍日期
        createOrderFactory.setBidDate();
        //设置竞拍开始时间
        createOrderFactory.setBeginTime();
        //设置竞拍结束时间
        createOrderFactory.setEndTime();
        //设置竞标挂牌量
        createOrderFactory.setBiddingW(bidweight);
        //设置最小交易量
        createOrderFactory.setMinWeight(minweight);
        //价格类型为商品价
        //设置联系人
        createOrderFactory.setLinkMan(linkman);
        //设置联系电话
        createOrderFactory.setContactPhone(contactphone);
        //设置交收方式为：协商交收
        createOrderFactory.setSettType1();
        //设置最大交易量
        createOrderFactory.setMaxWeight(maxweight);
        //设置交收周期：周
        createOrderFactory.setSettleCycle(settlecycle);
        //合同类型设置为：周合同
        createOrderFactory.setContractType_week();
        //设置销售对象类型为:天然气生产
        Thread.sleep(1000);
        createOrderFactory.setCompanyTypeView();
        //设置交收起始日
        createOrderFactory.setSettlementDate();
        //设置商品运输为：卖方包运
        createOrderFactory.setShipType_info();
        Thread.sleep(2000);
        //设置交收地点为：重庆
        createOrderFactory.setProvinceView2();
        //设置起拍价
        createOrderFactory.setBasePriceShow(baseprice);
        //设置最小变动价位
        createOrderFactory.setBidPerPrice(bidperprice);
        //设置最小交易单位
        createOrderFactory.setBidPerWeight(bidperpeight);
        //设置气化率
        createOrderFactory.setGasRate(gasRatenum);
        //点击保存并提交按钮
        createOrderFactory.setSubmmit();
        //确认提交按钮
        createOrderFactory.setSure();
        Thread.sleep(3000);
        //关闭浏览器
        driver.close();
    }

}
